package org.fundaciobit.pluginsib.validatesignature.esignature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.12
 * Mon Sep 17 13:15:23 CEST 2018
 * Generated source version: 2.2.12
 * 
 */
 
@WebService(targetNamespace = "http://validation.dss.esig.europa.eu/", name = "SoapDocumentValidationService")
@XmlSeeAlso({ObjectFactory.class})
public interface SoapDocumentValidationService {

    @WebMethod
    @RequestWrapper(localName = "validateSignature", targetNamespace = "http://validation.dss.esig.europa.eu/", className = "org.fundaciobit.pluginsib.validatesignature.esignature.ws.ValidateSignature")
    @ResponseWrapper(localName = "validateSignatureResponse", targetNamespace = "http://validation.dss.esig.europa.eu/", className = "org.fundaciobit.pluginsib.validatesignature.esignature.ws.ValidateSignatureResponse")
    @WebResult(name = "WSReportsDTO", targetNamespace = "")
    public org.fundaciobit.pluginsib.validatesignature.esignature.ws.WsReportsDTO validateSignature(
        @WebParam(name = "dataToValidateDTO", targetNamespace = "")
        org.fundaciobit.pluginsib.validatesignature.esignature.ws.DataToValidateDTO dataToValidateDTO
    );
}
