
/*
 * 
 */

package org.fundaciobit.pluginsib.validatesignature.esignature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.12
 * Mon Sep 17 13:15:23 CEST 2018
 * Generated source version: 2.2.12
 * 
 */


@WebServiceClient(name = "SoapDocumentValidationServiceImplService", 
                  wsdlLocation = "file:/C:/Users/fbosch/Documents/dades/programacio/PluginsIB-GovernIB/pluginsib-validatesignature/esignature/src/main/resources/wsdl/esignatureValidation.wsdl",
                  targetNamespace = "http://validation.dss.esig.europa.eu/") 
public class SoapDocumentValidationServiceImplService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://validation.dss.esig.europa.eu/", "SoapDocumentValidationServiceImplService");
    public final static QName SoapDocumentValidationServiceImplPort = new QName("http://validation.dss.esig.europa.eu/", "SoapDocumentValidationServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/fbosch/Documents/dades/programacio/PluginsIB-GovernIB/pluginsib-validatesignature/esignature/src/main/resources/wsdl/esignatureValidation.wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from file:/C:/Users/fbosch/Documents/dades/programacio/PluginsIB-GovernIB/pluginsib-validatesignature/esignature/src/main/resources/wsdl/esignatureValidation.wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public SoapDocumentValidationServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SoapDocumentValidationServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SoapDocumentValidationServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public SoapDocumentValidationServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }
    public SoapDocumentValidationServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public SoapDocumentValidationServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns SoapDocumentValidationService
     */
    @WebEndpoint(name = "SoapDocumentValidationServiceImplPort")
    public SoapDocumentValidationService getSoapDocumentValidationServiceImplPort() {
        return super.getPort(SoapDocumentValidationServiceImplPort, SoapDocumentValidationService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SoapDocumentValidationService
     */
    @WebEndpoint(name = "SoapDocumentValidationServiceImplPort")
    public SoapDocumentValidationService getSoapDocumentValidationServiceImplPort(WebServiceFeature... features) {
        return super.getPort(SoapDocumentValidationServiceImplPort, SoapDocumentValidationService.class, features);
    }

}
